[package]
name = "rust-database-common"
version = "0.1.0"
edition = "2024"

[dependencies]
deadpool-postgres = "0.14.1"
thiserror = "2.0.16"
tokio-postgres = { version = "0.7.13", features = ["with-chrono-0_4"] }
